Event api key auth 683/684
rokwire/rokwire-building-blocks-api pull request #691
Opened 2021-05-21 18:11 UTC by bingzhang

## Description
_Please provide a summary of the pull request and the issue it fixes. Please add necessary details, context, dependencies, explanation of when review is needed (see next section), etc._

**Fixes #(add issue number here and remove parentheses)**

[comment]: # (This project only accepts pull requests related to open issues.)
[comment]: # (If suggesting a new feature or change, please discuss it in an issue first.)
[comment]: # (If fixing a bug, there should be an issue describing it with steps to reproduce.)

## Review Time Estimate
_Please give your idea of how soon this pull request needs to be reviewed by selecting one of the options below. This can be based on the criticality of the issue at hand and/or other relevant factors._

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Immediately
- [ ] Within a week
- [ ] When possible

## Type of changes
_Please select a relevant option:_

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Other (any another change that does not fall in one of the above categories.)

## Checklist:
_Please select all applicable options:_

[comment]: # (To select your options, please put an 'x' in the all boxes that apply.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [ ] I have updated the [CHANGELOG](../CHANGELOG.md).
- [ ] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires updating the documentation.
- [ ] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [ ] My changes generate no new warnings.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

---

[comment]: # (Template credit: This pull request template is based on Embedded Artistry {https://github.com/embeddedartistry/templates/blob/master/.github/PULL_REQUEST_TEMPLATE.md}, Clowder {https://github.com/clowder-framework/clowder/blob/develop/.github/PULL_REQUEST_TEMPLATE.md}, and TalAter {https://github.com/TalAter/open-source-templates} templates.)

2021-05-21 18:13 UTC, bingzhang commented
@sandeep-ps it passed the test cases in my local db. need more tests though.

2021-05-27 15:20 UTC, sandeep-ps commented on eventservice/api/controllers/events.py
> +        if req.status_code == 200:
If there is an error communicating with Groups Building Block, Events Building Block should return HTTP 500 with an appropriate message in the response body.

2021-05-27 15:22 UTC, sandeep-ps commented on eventservice/api/controllers/events.py
> +        for cond in query.get('$and'):
I am getting an internal server error here when doing GET /events?category=Entertainment
```
2021-05-27T15:21:11.253Z ERROR   [Thread-2  ] : events_building_block - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "rokwire-building-blocks-api/eventservice/api/controllers/events.py", line 72, in search
    result, result_len = _get_events_result(
  File "rokwire-building-blocks-api/eventservice/venv/lib/python3.8/site-packages/diskcache/recipes.py", line 426, in wrapper
    pair = timer(*args, **kwargs)
  File "rokwire-building-blocks-api/eventservice/venv/lib/python3.8/site-packages/diskcache/recipes.py", line 385, in timer
    result = func(*args, **kwargs)
  File "rokwire-building-blocks-api/eventservice/api/controllers/events.py", line 101, in _get_events_result
    for cond in query.get('$and'):
TypeError: 'NoneType' object is not iterable

```

2021-06-01 17:01 UTC, sandeep-ps approved these changes

2021-06-01 17:02 UTC, sandeep-ps requested changes
@bingzhang, please update the CHANGELOG. Thanks.

2021-06-02 16:01 UTC, sandeep-ps commented on CHANGELOG.md
> +- Add group authentication to events building block.[#691](https://github.com/rokwire/rokwire-building-blocks-api/issues/683, https://github.com/rokwire/rokwire-building-blocks-api/issues/684)
```suggestion
- Add group authorization to events building block. [#683](https://github.com/rokwire/rokwire-building-blocks-api/issues/683), [#684](https://github.com/rokwire/rokwire-building-blocks-api/issues/684)
```

2021-06-02 20:53 UTC, sandeep-ps approved these changes

2021-06-02 20:54 UTC, merged